"""Define enumeration constants for HTTP status Mozilla docs."""

from enum import StrEnum


class HTTPStatusDoc(StrEnum):
    """Enumeration of Mozilla documentation links for HTTP status codes."""

    HTTP_STATUS_100 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/100"
    HTTP_STATUS_101 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/101"
    HTTP_STATUS_102 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/102"
    HTTP_STATUS_200 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/200"
    HTTP_STATUS_201 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/201"
    HTTP_STATUS_202 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/202"
    HTTP_STATUS_203 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/203"
    HTTP_STATUS_204 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/204"
    HTTP_STATUS_205 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/205"
    HTTP_STATUS_206 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/206"
    HTTP_STATUS_207 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/207"
    HTTP_STATUS_208 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/208"
    HTTP_STATUS_226 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/226"
    HTTP_STATUS_300 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/300"
    HTTP_STATUS_301 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/301"
    HTTP_STATUS_302 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/302"
    HTTP_STATUS_303 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/303"
    HTTP_STATUS_304 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/304"
    HTTP_STATUS_305 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/305"
    HTTP_STATUS_307 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/307"
    HTTP_STATUS_308 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308"
    HTTP_STATUS_400 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400"
    HTTP_STATUS_401 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/401"
    HTTP_STATUS_402 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/402"
    HTTP_STATUS_403 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403"
    HTTP_STATUS_404 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404"
    HTTP_STATUS_405 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/405"
    HTTP_STATUS_406 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/406"
    HTTP_STATUS_407 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/407"
    HTTP_STATUS_408 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/408"
    HTTP_STATUS_409 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/409"
    HTTP_STATUS_410 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410"
    HTTP_STATUS_411 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/411"
    HTTP_STATUS_412 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/412"
    HTTP_STATUS_413 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/413"
    HTTP_STATUS_414 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414"
    HTTP_STATUS_415 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/415"
    HTTP_STATUS_416 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/416"
    HTTP_STATUS_417 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/417"
    HTTP_STATUS_418 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/418"
    HTTP_STATUS_421 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/421"
    HTTP_STATUS_422 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/422"
    HTTP_STATUS_423 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/423"
    HTTP_STATUS_424 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/424"
    HTTP_STATUS_425 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/425"
    HTTP_STATUS_426 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/426"
    HTTP_STATUS_428 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/428"
    HTTP_STATUS_429 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429"
    HTTP_STATUS_431 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431"
    HTTP_STATUS_451 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/451"
    HTTP_STATUS_500 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/500"
    HTTP_STATUS_501 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/501"
    HTTP_STATUS_502 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/502"
    HTTP_STATUS_503 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/503"
    HTTP_STATUS_504 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/504"
    HTTP_STATUS_505 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/505"
    HTTP_STATUS_506 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/506"
    HTTP_STATUS_507 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/507"
    HTTP_STATUS_508 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/508"
    HTTP_STATUS_510 = "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/510"
    HTTP_STATUS_511 = (
        "https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/511HTTP_"
    )
